package com.sjl.bookmark.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sjl.bookmark.entity.table.Bookmark;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOKMARK".
*/
public class BookmarkDao extends AbstractDao<Bookmark, Long> {

    public static final String TABLENAME = "BOOKMARK";

    /**
     * Properties of entity Bookmark.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Href = new Property(3, String.class, "href", false, "HREF");
        public final static Property Icon = new Property(4, String.class, "icon", false, "ICON");
        public final static Property Text = new Property(5, String.class, "text", false, "TEXT");
        public final static Property Date = new Property(6, java.util.Date.class, "date", false, "DATE");
        public final static Property SourceFile = new Property(7, String.class, "sourceFile", false, "SOURCE_FILE");
    }


    public BookmarkDao(DaoConfig config) {
        super(config);
    }
    
    public BookmarkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOKMARK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"TITLE\" TEXT NOT NULL ," + // 2: title
                "\"HREF\" TEXT," + // 3: href
                "\"ICON\" TEXT," + // 4: icon
                "\"TEXT\" TEXT," + // 5: text
                "\"DATE\" INTEGER NOT NULL ," + // 6: date
                "\"SOURCE_FILE\" TEXT);"); // 7: sourceFile
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BOOKMARK_TITLE ON \"BOOKMARK\"" +
                " (\"TITLE\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_BOOKMARK_TEXT ON \"BOOKMARK\"" +
                " (\"TEXT\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_BOOKMARK_SOURCE_FILE ON \"BOOKMARK\"" +
                " (\"SOURCE_FILE\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOKMARK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Bookmark entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindString(3, entity.getTitle());
 
        String href = entity.getHref();
        if (href != null) {
            stmt.bindString(4, href);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(5, icon);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(6, text);
        }
        stmt.bindLong(7, entity.getDate().getTime());
 
        String sourceFile = entity.getSourceFile();
        if (sourceFile != null) {
            stmt.bindString(8, sourceFile);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Bookmark entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindString(3, entity.getTitle());
 
        String href = entity.getHref();
        if (href != null) {
            stmt.bindString(4, href);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(5, icon);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(6, text);
        }
        stmt.bindLong(7, entity.getDate().getTime());
 
        String sourceFile = entity.getSourceFile();
        if (sourceFile != null) {
            stmt.bindString(8, sourceFile);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Bookmark readEntity(Cursor cursor, int offset) {
        Bookmark entity = new Bookmark( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // href
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // icon
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // text
            new java.util.Date(cursor.getLong(offset + 6)), // date
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // sourceFile
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Bookmark entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setTitle(cursor.getString(offset + 2));
        entity.setHref(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIcon(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setText(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDate(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setSourceFile(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Bookmark entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Bookmark entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Bookmark entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
