package com.sjl.bookmark.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.sjl.bookmark.entity.zhuishu.table.BookChapter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_CHAPTER".
*/
public class BookChapterDao extends AbstractDao<BookChapter, String> {

    public static final String TABLENAME = "BOOK_CHAPTER";

    /**
     * Properties of entity BookChapter.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Link = new Property(1, String.class, "link", false, "LINK");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property TaskName = new Property(3, String.class, "taskName", false, "TASK_NAME");
        public final static Property Unreadble = new Property(4, boolean.class, "unreadble", false, "UNREADBLE");
        public final static Property BookId = new Property(5, String.class, "bookId", false, "BOOK_ID");
        public final static Property Start = new Property(6, long.class, "start", false, "START");
        public final static Property End = new Property(7, long.class, "end", false, "END");
    }

    private Query<BookChapter> collectBook_BookChapterListQuery;

    public BookChapterDao(DaoConfig config) {
        super(config);
    }
    
    public BookChapterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_CHAPTER\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"LINK\" TEXT," + // 1: link
                "\"TITLE\" TEXT," + // 2: title
                "\"TASK_NAME\" TEXT," + // 3: taskName
                "\"UNREADBLE\" INTEGER NOT NULL ," + // 4: unreadble
                "\"BOOK_ID\" TEXT," + // 5: bookId
                "\"START\" INTEGER NOT NULL ," + // 6: start
                "\"END\" INTEGER NOT NULL );"); // 7: end
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BOOK_CHAPTER_BOOK_ID ON \"BOOK_CHAPTER\"" +
                " (\"BOOK_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_CHAPTER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookChapter entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(2, link);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String taskName = entity.getTaskName();
        if (taskName != null) {
            stmt.bindString(4, taskName);
        }
        stmt.bindLong(5, entity.getUnreadble() ? 1L: 0L);
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(6, bookId);
        }
        stmt.bindLong(7, entity.getStart());
        stmt.bindLong(8, entity.getEnd());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookChapter entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(2, link);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String taskName = entity.getTaskName();
        if (taskName != null) {
            stmt.bindString(4, taskName);
        }
        stmt.bindLong(5, entity.getUnreadble() ? 1L: 0L);
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(6, bookId);
        }
        stmt.bindLong(7, entity.getStart());
        stmt.bindLong(8, entity.getEnd());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookChapter readEntity(Cursor cursor, int offset) {
        BookChapter entity = new BookChapter( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // link
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // taskName
            cursor.getShort(offset + 4) != 0, // unreadble
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // bookId
            cursor.getLong(offset + 6), // start
            cursor.getLong(offset + 7) // end
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookChapter entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLink(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTaskName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUnreadble(cursor.getShort(offset + 4) != 0);
        entity.setBookId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStart(cursor.getLong(offset + 6));
        entity.setEnd(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookChapter entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(BookChapter entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookChapter entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bookChapterList" to-many relationship of CollectBook. */
    public List<BookChapter> _queryCollectBook_BookChapterList(String bookId) {
        synchronized (this) {
            if (collectBook_BookChapterListQuery == null) {
                QueryBuilder<BookChapter> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BookId.eq(null));
                collectBook_BookChapterListQuery = queryBuilder.build();
            }
        }
        Query<BookChapter> query = collectBook_BookChapterListQuery.forCurrentThread();
        query.setParameter(0, bookId);
        return query.list();
    }

}
