package com.sjl.bookmark.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sjl.bookmark.entity.table.BrowseTrack;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BROWSE_TRACK".
*/
public class BrowseTrackDao extends AbstractDao<BrowseTrack, Long> {

    public static final String TABLENAME = "BROWSE_TRACK";

    /**
     * Properties of entity BrowseTrack.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ArticleId = new Property(1, String.class, "articleId", false, "ARTICLE_ID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Href = new Property(3, String.class, "href", false, "HREF");
        public final static Property Text = new Property(4, String.class, "text", false, "TEXT");
        public final static Property Category = new Property(5, String.class, "category", false, "CATEGORY");
        public final static Property CreateTime = new Property(6, java.util.Date.class, "createTime", false, "CREATE_TIME");
    }


    public BrowseTrackDao(DaoConfig config) {
        super(config);
    }
    
    public BrowseTrackDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BROWSE_TRACK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ARTICLE_ID\" TEXT NOT NULL ," + // 1: articleId
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"HREF\" TEXT," + // 3: href
                "\"TEXT\" TEXT," + // 4: text
                "\"CATEGORY\" TEXT," + // 5: category
                "\"CREATE_TIME\" INTEGER);"); // 6: createTime
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BROWSE_TRACK_TYPE ON \"BROWSE_TRACK\"" +
                " (\"TYPE\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_BROWSE_TRACK_TEXT ON \"BROWSE_TRACK\"" +
                " (\"TEXT\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BROWSE_TRACK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BrowseTrack entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getArticleId());
        stmt.bindLong(3, entity.getType());
 
        String href = entity.getHref();
        if (href != null) {
            stmt.bindString(4, href);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(5, text);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(7, createTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BrowseTrack entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getArticleId());
        stmt.bindLong(3, entity.getType());
 
        String href = entity.getHref();
        if (href != null) {
            stmt.bindString(4, href);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(5, text);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(7, createTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BrowseTrack readEntity(Cursor cursor, int offset) {
        BrowseTrack entity = new BrowseTrack( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // articleId
            cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // href
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // text
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // category
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BrowseTrack entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setArticleId(cursor.getString(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setHref(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setText(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCategory(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreateTime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BrowseTrack entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BrowseTrack entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BrowseTrack entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
